services:
  plex:
    instances: 1
    image: plexinc/pms-docker
    tag: plexpass
    network_mode: host
    privileged: True
    devices:
      - /dev/dri:/dev/dri
    environment:
      TZ: "Europe/Stockholm"
      PLEX_UID: "1001"
      PLEX_GID: "1001"
    volumes:
      - /opt/plex/config:/config
      - /tmp/transcode:/transcode
      - /mnt/media:/mnt/media
    labels:
      - "traefik.enable=true"
      - "traefik.backend=plex"
      - "traefik.frontend.rule=Host:plex.lan"
      - "traefik.port=32400"
  murmur:
    instances: 1
    image: ivarmedi/murmur
    tag: 1.2.11
    network_mode: host
    labels:
      - "traefik.enable=false"
  homeassistant:
    instances: 1
    image: homeassistant/home-assistant
    network_mode: host
    files:
      -
        source: salt://homeassistant/files/configuration.yaml
        path: /etc/homeassistant/configuration.yaml
        mode: "0644"
        user: "root"
        group: "root"
    volumes:
      - /etc/localtime:/etc/localtime
      - /etc/homeassistant:/config
    labels:
      - "traefik.enable=true"
      - "traefik.backend=homeassistant"
      - "traefik.frontend.rule=Host:homeassistant.lan"
      - "traefik.port=8123"
  mosquitto:
    instances: 1
    image: toke/mosquitto
    ports:
      - 1883:1883
    volumes:
      - /etc/mosquitto:/mqtt/config:ro
    files:
      -
        source: salt://mosquitto/files/mosquitto.conf
        path: /etc/mosquitto/mosquitto.conf
        mode: "0644"
        user: "root"
        group: "root"
    labels:
      - "traefik.enable=false"
  telldusd:
    instances: 1
    image: ivarmedi/telldusd
    ports:
      - 50800:50800
      - 50801:50801
    volumes:
      - /etc/tellstick/tellstick.conf:/etc/tellstick.conf
    privileged: True
    files:
      -
        source: salt://telldusd/files/tellstick.conf
        path: /etc/tellstick/tellstick.conf
        mode: "0644"
        user: "root"
        group: "root"
    labels:
      - "traefik.enable=false"
  tvheadend:
    instances: 1
    image: linuxserver/tvheadend
    ports:
      - 9981:9981
      - 9982:9982
    volumes:
      - /etc/tvheadend:/config
      - /mnt/media/Recordings:/recordings
    environment:
      TZ: "Europe/Stockholm"
    labels:
      - "traefik.enable=true"
      - "traefik.backend=tvheadend"
      - "traefik.frontend.rule=Host:tvheadend.lan"
      - "traefik.port=9981"
  znc:
    instances: 1
    image: znc
    ports:
      - 6697:6697
    volumes:
      - /etc/znc:/znc-data
    labels:
      - "traefik.enable=true"
      - "traefik.backend=znc"
      - "traefik.frontend.rule=Host:znc.lan"
      - "traefik.port=6697"
  sonarr:
    instances: 1
    image: linuxserver/sonarr
    ports:
      - 8989:8989
    volumes:
      - /etc/sonarr:/config
      - /mnt/media/Serier:/tv
      - /mnt/media/Downloads:/downloads
    environment:
      TZ: "Europe/Stockholm"
      PUID: 1001
      PGID: 1001
    labels:
      - "traefik.enable=true"
      - "traefik.backend=sonarr"
      - "traefik.frontend.rule=Host:sonarr.lan"
      - "traefik.port=8989"
  radarr:
    instances: 1
    image: linuxserver/radarr
    ports:
      - 7878:7878
    volumes:
      - /etc/radarr:/config
      - /mnt/media/Filmer:/movies
      - /mnt/media/Downloads:/downloads
    environment:
      TZ: "Europe/Stockholm"
      PUID: 1001
      PGID: 1001
    labels:
      - "traefik.enable=true"
      - "traefik.backend=radarr"
      - "traefik.frontend.rule=Host:radarr.lan"
      - "traefik.port=7878"
  jackett:
    instances: 1
    image: linuxserver/jackett
    ports:
      - 9117:9117
    volumes:
      - /etc/jackett:/config
      - /mnt/media/Downloads:/downloads
    environment:
      TZ: "Europe/Stockholm"
      PUID: 1001
      PGID: 1001
    labels:
      - "traefik.enable=true"
      - "traefik.backend=jackett"
      - "traefik.frontend.rule=Host:jackett.lan"
      - "traefik.port=9117"
  ombi:
    instances: 1
    image: linuxserver/ombi
    ports:
      - 3579:3579
    volumes:
      - /etc/ombi:/config
    environment:
      TZ: "Europe/Stockholm"
      PUID: 1001
      PGID: 1001
    labels:
      - "traefik.enable=true"
      - "traefik.backend=ombi"
      - "traefik.frontend.rule=Host:ombi.lan"
      - "traefik.port=3579"
  traefik:
    instances: 1
    image: traefik
    network_mode: host
    volumes:
      - /etc/traefik/traefik.toml:/etc/traefik/traefik.toml
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/ssl/traefik:/etc/ssl/traefik
    labels:
      - "traefik.enable=true"
      - "traefik.backend=traefik"
      - "traefik.frontend.rule=Host:traefik.lan"
      - "traefik.port=8080"
  squid:
    instances: 1
    image: ivarmedi/squid
    files:
      -
        source: salt://squid/files/squid.conf
        path: /etc/squid/squid.conf
        mode: "0644"
        user: "root"
        group: "root"
    ports:
      - 3128:3128
      - 3130:3130
    volumes:
      - /etc/squid/cache:/var/spool/squid
      - /etc/squid/ssl:/etc/ssl/squid
      - /etc/squid/squid.conf:/etc/squid/squid.conf
      - /var/log/containers/squid:/var/log/squid
    environment:
      TZ: "Europe/Stockholm"
    labels:
      - "traefik.enable=false"
  portainer:
    instances: 1
    image: portainer/portainer
    ports:
      - 9000:9000
    volumes:
      - /etc/portainer:/data
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - "traefik.enable=true"
      - "traefik.backend=portainer"
      - "traefik.frontend.rule=Host:portainer.lan"
      - "traefik.port=9000"
  deluge:
    instances: 1
    image: binhex/arch-delugevpn
    tag: 2.0.3_23_g5f1eada3e-1-03
    ports:
      - 8112:8112
      - 8118:8118
      - 58846:58846
      - 58946:58946
    volumes:
      - /mnt/media/Downloads:/export/media/Downloads
      - /etc/deluge:/config
      - /etc/localtime:/etc/localtime
    cap_add:
      - NET_ADMIN
    environment:
      VPN_ENABLED: 'yes'
      VPN_PROV: 'custom'
      STRICT_PORT_FORWARD: 'yes'
      ENABLE_PRIVOXY: 'no'
      LAN_NETWORK: '192.168.137.0/24,192.168.138.0/24,10.8.0.0/24'
      NAME_SERVERS: '209.222.18.222,37.235.1.174,8.8.8.8,209.222.18.218,37.235.1.177,8.8.4.4'
      PUID: 1001
      GUID: 1001
      DEBUG: true
  postgres:
    instances: 1
    image: postgres
    tag: 11-alpine
    ports:
      - 5432:5432
    volumes:
      - /var/lib/postgresql/data:/var/lib/postgresql/data
      - /etc/postgresql:/etc/postgresql
    environment:
      POSTGRES_PASSWORD_FILE: /etc/postgresql/password
  postfix:
    instances: 1
    image: catatnight/postfix
    network_mode: host
    volumes:
      - /etc/postfix/certs:/etc/postfix/certs:ro
      - /etc/postfix/main.cf:/etc/postfix/main.cf:ro
      - /etc/postfix/master.cf:/etc/postfix/master.cf:ro
    environment:
      maildomain: hemma.larsson.me
  meta:
    instances: 1
    image: ivarmedi/meta.sr.ht
    ports:
      - 8001:8001
    volumes:
      - /etc/sr.ht/config.ini:/etc/sr.ht/config.ini
    labels:
      - "traefik.enable=true"
      - "traefik.backend=meta"
      - "traefik.frontend.rule=Host:meta.lan"
      - "traefik.port=8001"
  pihole:
    instances: 1
    image: pihole/pihole
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 67:67/udp
      - 8002:80/tcp
    environment:
      TZ: 'Europe/Stockholm'
    volumes:
      - /etc/pihole/config/:/etc/pihole/
      - /etc/pihole/dnsmasq.d/:/etc/dnsmasq.d/
    dns:
      - 192.168.137.1
    labels:
      - "traefik.enable=true"
      - "traefik.backend=pihole"
      - "traefik.frontend.rule=Host:pihole.lan"
      - "traefik.port=8002"
  nginx:
    instances: 1
    image: nginx
    network_mode: host
    volumes:
      - /etc/nginx:/etc/nginx:ro
      - /etc/certbot/conf:/etc/letsencrypt:ro
      - /etc/certbot/www:/var/www/certbot:ro
  certbot:
    instances: 1
    image: certbot/certbot
    volumes:
      - /etc/certbot/conf:/etc/letsencrypt:rw
      - /etc/certbot/www:/var/www/certbot:rw
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h; done;'"
  selenium_hub:
    instances: 1
    image: selenium/hub
    networks:
      - selenium_grid
    ports:
      - 4444:4444/tcp
  selenium_node_chrome:
    instances: 2
    image: selenium/node-chrome
    environment:
      HUB_HOST: selenium_hub-0
    networks:
      - selenium_grid
    volumes:
      - /dev/shm:/dev/shm
  selenium_node_firefox:
    instances: 2
    image: selenium/node-firefox
    environment:
      HUB_HOST: selenium_hub-0
    networks:
      - selenium_grid
    volumes:
      - /dev/shm:/dev/shm
applications:
  ivli_api:
    instances: 1
    image: node
    tag: 12
    ports:
      - 3003:3003/tcp
    volumes:
      - /var/www/ivli_api:/var/www/ivli_api
      - /var/www/ivli_frontend:/var/www/ivli_frontend
    environment:
      NODE_ENV: production
    workdir: /var/www/ivli_api
    command: node_modules/nodemon/bin/nodemon.js
