services:
  plex:
    instances: 1
    image: plexinc/pms-docker
    tag: plexpass
    network_mode: host
    environment:
      TZ: "Europe/Stockholm"
      PLEX_UID: "1001"
      PLEX_GID: "1001"
    volumes:
      - /opt/plex/config:/config
      - /tmp/transcode:/transcode
      - /mnt/media:/mnt/media
    labels:
      - "traefik.enable=true"
      - "traefik.backend=plex"
      - "traefik.frontend.rule=Host:plex.local"
      - "traefik.port=32400"
  murmur:
    instances: 1
    image: ivarmedi/murmur
    tag: 1.2.11
    network_mode: host
    labels:
      - "traefik.enable=false"
  homeassistant:
    instances: 1
    image: homeassistant/home-assistant
    network_mode: host
    files:
      -
        source: salt://homeassistant/files/configuration.yaml
        path: /etc/homeassistant/configuration.yaml
        mode: "0644"
        user: "root"
        group: "root"
    volumes:
      - /etc/localtime:/etc/localtime
      - /etc/homeassistant:/config
    labels:
      - "traefik.enable=true"
      - "traefik.backend=homeassistant"
      - "traefik.frontend.rule=Host:homeassistant.local"
      - "traefik.port=8123"
  mosquitto:
    instances: 1
    image: toke/mosquitto
    ports:
      - 1883:1883
    volumes:
      - /etc/mosquitto:/mqtt/config:ro
    files:
      -
        source: salt://mosquitto/files/mosquitto.conf
        path: /etc/mosquitto/mosquitto.conf
        mode: "0644"
        user: "root"
        group: "root"
    labels:
      - "traefik.enable=false"
  telldusd:
    instances: 1
    image: ivarmedi/telldusd
    ports:
      - 50800:50800
      - 50801:50801
    volumes:
      - /etc/tellstick/tellstick.conf:/etc/tellstick.conf
    privileged: True
    files:
      -
        source: salt://telldusd/files/tellstick.conf
        path: /etc/tellstick/tellstick.conf
        mode: "0644"
        user: "root"
        group: "root"
    labels:
      - "traefik.enable=false"
  tvheadend:
    instances: 1
    image: linuxserver/tvheadend
    ports:
      - 9981:9981
      - 9982:9982
    volumes:
      - /etc/tvheadend:/config
      - /mnt/media/Recordings:/recordings
    environment:
      TZ: "Europe/Stockholm"
    labels:
      - "traefik.enable=true"
      - "traefik.backend=tvheadend"
      - "traefik.frontend.rule=Host:tvheadend.local"
      - "traefik.port=9981"
  znc:
    instances: 1
    image: znc
    ports:
      6697:6697
    volumes:
      - /etc/znc:/znc-data
    labels:
      - "traefik.enable=true"
      - "traefik.backend=znc"
      - "traefik.frontend.rule=Host:znc.local"
      - "traefik.port=6697"
  sonarr:
    instances: 1
    image: linuxserver/sonarr
    ports:
      8989:8989
    volumes:
      - /etc/sonarr:/config
      - /mnt/media/Serier:/tv
      - /mnt/media/Downloads:/downloads
    environment:
      TZ: "Europe/Stockholm"
      PUID: 1001
      PGID: 1001
    labels:
      - "traefik.enable=true"
      - "traefik.backend=sonarr"
      - "traefik.frontend.rule=Host:sonarr.local"
      - "traefik.port=8989"
  radarr:
    instances: 1
    image: linuxserver/radarr
    ports:
      7878:7878
    volumes:
      - /etc/radarr:/config
      - /mnt/media/Filmer:/movies
      - /mnt/media/Downloads:/downloads
    environment:
      TZ: "Europe/Stockholm"
      PUID: 1001
      PGID: 1001
    labels:
      - "traefik.enable=true"
      - "traefik.backend=radarr"
      - "traefik.frontend.rule=Host:radarr.local"
      - "traefik.port=7878"
  jackett:
    instances: 1
    image: linuxserver/jackett
    ports:
      9117:9117
    volumes:
      - /etc/jackett:/config
      - /mnt/media/Downloads:/downloads
    environment:
      TZ: "Europe/Stockholm"
      PUID: 1001
      PGID: 1001
    labels:
      - "traefik.enable=true"
      - "traefik.backend=jackett"
      - "traefik.frontend.rule=Host:jackett.local"
      - "traefik.port=9117"
  ombi:
    instances: 1
    image: linuxserver/ombi
    ports:
      3579:3579
    volumes:
      /etc/ombi:/config
    environment:
      TZ: "Europe/Stockholm"
      PUID: 1001
      PGID: 1001
    labels:
      - "traefik.enable=true"
      - "traefik.backend=ombi"
      - "traefik.frontend.rule=Host:ombi.local"
      - "traefik.port=3579"
  traefik:
    instances: 1
    image: traefik
    ports:
      - 443:443
      - 80:80
      - 8080:8080
    volumes:
      - /etc/traefik/traefik.toml:/etc/traefik/traefik.toml
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - "traefik.enable=false"
