services:
  plex:
    instances: 1
    image: plexinc/pms-docker
    tag: plexpass
    network_mode: host
    environment:
      TZ: "Europe/Stockholm"
      PLEX_UID: "1001"
      PLEX_GID: "1001"
    volumes:
      - /opt/plex/config:/config
      - /tmp/transcode:/transcode
      - /mnt/media:/mnt/media
  murmur:
    instances: 1
    image: ivarmedi/murmur
    tag: 1.2.11
    network_mode: host
  homeassistant:
    instances: 1
    image: homeassistant/home-assistant
    network_mode: host
    files:
      -
        source: salt://homeassistant/files/configuration.yaml
        path: /etc/homeassistant/configuration.yaml
        mode: 0644
        user: root
        group: root
    volumes:
      - /etc/localtime:/etc/localtime
      - /etc/homeassistant:/config
  mosquitto:
    instances: 1
    image: toke/mosquitto
    ports:
      - 1883:1883
    volumes:
      - /etc/mosquitto:/mqtt/config:ro
    files:
      -
        source: salt://mosquitto/files/mosquitto.conf
        path: /etc/mosquitto/mosquitto.conf
        mode: 0644
        user: root
        group: root
